# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.12-slim

ARG HOST_DIR=/Users

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home

RUN mkdir -p $DAGSTER_HOME

COPY . $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

RUN pip install -r requirements.txt

RUN ipython kernel install --name anaconda3 --user

COPY ./dagster-prod.yaml $DAGSTER_HOME/dagster.yaml

COPY ./workspace-prod.yaml $DAGSTER_HOME/workspace.yaml

RUN sed -i  "s|\${HOME_DIR}|$HOST_DIR|g" dagster.yaml

VOLUME /opt/dagster/dagster_home/data