name: apdv
dependencies:
  - python=3.12
  - pandas
  - seaborn
  - pymongo
  - notebook
  - scikit-learn
  - nbconvert
  - ipython
  - ipykernel
  - matplotlib
  - plotly
  - requests
  - six
  - numpy
  - ipywidgets
  - dash
  - flask-cors
  - dnspython
  - idna
  - httpcore
  - httpx
  - cryptography
  - anyio
  - defusedxml
  - pillow
  - pip
  - attrs
  - wheel
  - protobuf
  - tornado
  - jinja2
  - flask
  - importlib-metadata
  - beautifulsoup4
  - psutil
  - nest-asyncio
  - werkzeug
  - retrying
  - coloredlogs
  - pyyaml
  - grpcio
  - mako
  - babel
  - pygments
  - markupsafe
  - pytz
  - rich
  - markdown-it-py
  - zipp
  - click
  - blinker
  - itsdangerous
  - mdurl
  - charset-normalizer
  - setuptools
  - overrides
  - cffi
  - scipy
  - threadpoolctl
  - platformdirs
  - fsspec
  - antlr4-python3-runtime
  - aiohttp
  - yarl
  - joblib
  - pyarrow
  - sqlalchemy
  - python-dateutil
  - tenacity
  - packaging
  - traitlets
  - alembic
  - certifi
  - tqdm
  - tomli
  - python-dotenv
  - watchdog
  - pydantic
  - filelock
  - urllib3
  - deprecated
  - annotated-types
  - wcwidth
  - contourpy
  - fonttools
  - pyparsing
  - decorator
  - cycler
  - kiwisolver
  - humanfriendly
  - pandas
  - pymongo
  - scikit-learn
  - matplotlib
  - plotly
  - requests
  - six
  - numpy
  - dash
  - flask-cors